//Exercise 15.28: Define a vector to hold Quote objects but put
//Bulk_quote objects into that vector. Compute the total net_price of all
//the elements in the vector.
//Exercise 15.29: Repeat your program, but this time store shared_ptrs to
//objects of type Quote. Explain any discrepancy in the sum generated by the
//this version and the previous program. If there is no discrepancy, explain why
//there isn’t one.

#include "../15-5/Bulk_quote.h"
#include <vector>
#include <memory>
int main()
{
    std::vector<Quote> vecQ;
    Bulk_quote first("a",10.2,10,0.3);
    Bulk_quote second("a",20.2,10,0.3);
    vecQ.push_back(first);
    vecQ.push_back(second);
    auto sum = vecQ[0].net_price(20) + vecQ[1].net_price(20);
    std::cout << "Acual Obj: " << sum << std::endl;
    std::vector<std::shared_ptr<Quote>> vec;
    vec.push_back(std::make_shared<Bulk_quote>("a",10.2,10,0.5));
    vec.push_back(std::make_shared<Bulk_quote>("a",20.2,10,0.5));
    auto sum2 = vec[0]->net_price(20) + vec[1]->net_price(20);
    std::cout << "Pointers: " << sum2 << std::endl;
    return 0;
}
